dataset: CIFAR10
iid: IID # IID | Non_IID_Dirichlet | Non_IID_Quantity_Based | Non_IID_Qunatity_Skew | Non_IID_Noise
fl_strategy: FedProx # FedAvg | FedProx
num_clients: 3
list_of_epochs: [2,2,2]
same_initial_weights: true
n_rounds: 2

mu: 0.01
beta: null
labels_per_party: null
noise_level: null

batch_size: 10
lr: 1e-4
